// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsxXncmWMeWirrwHcSDXYPqGa1ns61NhQ',
    appId: '1:74291696584:web:dd56b491776d8e5baea6fd',
    messagingSenderId: '74291696584',
    projectId: 'digital-awareness-da814',
    authDomain: 'digital-awareness-da814.firebaseapp.com',
    storageBucket: 'digital-awareness-da814.appspot.com',
    measurementId: 'G-7DYQPQJP9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoTsnLbBI91PLQex7v_P_Vab1Xu3X-2M',
    appId: '1:74291696584:android:e78ea214448bba0baea6fd',
    messagingSenderId: '74291696584',
    projectId: 'digital-awareness-da814',
    storageBucket: 'digital-awareness-da814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdr5fY7vv88T4HP2NkyCSqf0HhEAOzlDQ',
    appId: '1:74291696584:ios:78f751e50d62ab7aaea6fd',
    messagingSenderId: '74291696584',
    projectId: 'digital-awareness-da814',
    storageBucket: 'digital-awareness-da814.appspot.com',
    iosBundleId: 'com.example.digitalAwarenessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdr5fY7vv88T4HP2NkyCSqf0HhEAOzlDQ',
    appId: '1:74291696584:ios:78f751e50d62ab7aaea6fd',
    messagingSenderId: '74291696584',
    projectId: 'digital-awareness-da814',
    storageBucket: 'digital-awareness-da814.appspot.com',
    iosBundleId: 'com.example.digitalAwarenessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsxXncmWMeWirrwHcSDXYPqGa1ns61NhQ',
    appId: '1:74291696584:web:9e2f221de722fc38aea6fd',
    messagingSenderId: '74291696584',
    projectId: 'digital-awareness-da814',
    authDomain: 'digital-awareness-da814.firebaseapp.com',
    storageBucket: 'digital-awareness-da814.appspot.com',
    measurementId: 'G-MXC5PZSNZ3',
  );
}
